<a href="https://colab.research.google.com/github/eashwardarur/DA/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing
ENCODING

Label Encoding

In [ ]:
#Importing the modules
import pandas as pd
#scikit-learn its an library
#preprocessing module
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#LabelEncoder is class

In [ ]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [ ]:
df['Product'].unique()

array(['Watch', 'Mouse', 'stove', 'shoe'], dtype=object)

In [ ]:
le=LabelEncoder()

In [ ]:
#fit will learn the data,identify the unique vales,sort them and map them
#transform will transfrom the data
#.fit() and .transform()
#fit_transform accepts one positional argument
df['Product']=le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2

One Hot Encoder

In [ ]:
import pandas as pd
#scikit-learn its an library
#preprocessing module
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
#OneHotEncoder is class

In [ ]:
df1=pd.DataFrame({
    'Gadgets':['Watch','Mobile','Mobile','mobile','Tablets','ipad','Watch']

})
df

   Gadgets
0    Watch
1   Mobile
2   Mobile
3   mobile
4  Tablets
5     ipad
6    Watch

In [ ]:
data= ohe.fit_transform(df1[['Gadgets']])
name=ohe.get_feature_names_out(['Gadgets'])
df1= pd.DataFrame(data,columns=name)

In [ ]:
df1

   Gadgets_Mobile  Gadgets_Tablets  Gadgets_Watch  Gadgets_ipad  Gadgets_mobile
0             0.0              0.0            1.0           0.0             0.0
1             1.0              0.0            0.0           0.0             0.0
2             1.0              0.0            0.0           0.0             0.0
3             0.0              0.0            0.0           0.0             1.0
4             0.0              1.0            0.0           0.0             0.0
5             0.0              0.0            0.0           1.0             0.0
6             0.0              0.0            1.0           0.0             0.0

In [ ]:
data

array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
name

array(['Gadgets_Mobile', 'Gadgets_Tablets', 'Gadgets_Watch',
       'Gadgets_ipad', 'Gadgets_mobile'], dtype=object)

Examples on OneHotEncoder

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df3=pd.DataFrame({'Batches':['A1','A1','M24','M168','M19','M19','M24']}
                )
ohe=OneHotEncoder(sparse_output=False)
data8=ohe.fit_transform(df3[['Batches']])
name=ohe.get_feature_names_out(['Batches'])
df3=pd.DataFrame(data8,columns=name)
df3

   Batches_A1  Batches_M168  Batches_M19  Batches_M24
0         1.0           0.0          0.0          0.0
1         1.0           0.0          0.0          0.0
2         0.0           0.0          0.0          1.0
3         0.0           1.0          0.0          0.0
4         0.0           0.0          1.0          0.0
5         0.0           0.0          1.0          0.0
6         0.0           0.0          0.0          1.0

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df2=pd.DataFrame({'Actors':['ALLU ARJUN','PRABHAS','SALMAN KHAN','RANBIR KAPOOR','RANVEER','ALLU ARJUN','PRABHAS']}
                )
ohe=OneHotEncoder(sparse_output=False)
dataa=ohe.fit_transform(df2[['Actors']])
name=ohe.get_feature_names_out(['Actors'])
df2=pd.DataFrame(dataa,columns=name)
df2

,Actors_ALLU ARJUN,Actors_PRABHAS,Actors_RANBIR KAPOOR,Actors_RANVEER,Actors_SALMAN KHAN
0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,0.0,0.0
6,0.0,1.0,0.0,0.0,0.0

Without using OneHotEncoder()

*   Using only pandas

In [2]:
import pandas as pd
df0=pd.DataFrame({'Actors':['ALLU ARJUN','PRABHAS','SALMAN KHAN','RANBIR KAPOOR','RANVEER','ALLU ARJUN','PRABHAS']}
                )
df0_Encoded=pd.get_dummies(df0,columns=['Actors'],dtype=int)
df0_Encoded

,Actors_ALLU ARJUN,Actors_PRABHAS,Actors_RANBIR KAPOOR,Actors_RANVEER,Actors_SALMAN KHAN
0,1,0,0,0,0
1,0,1,0,0,0
2,0,0,0,0,1
3,0,0,1,0,0
4,0,0,0,1,0
5,1,0,0,0,0
6,0,1,0,0,0

In [3]:
import pandas as pd
df0=pd.DataFrame({'Batches':['A1','A1','M24','M168','M19','M19','M24']}
                )
df0_Encoded=pd.get_dummies(df0,columns=['Batches'],dtype=int)
df0_Encoded

   Batches_A1  Batches_M168  Batches_M19  Batches_M24
0           1             0            0            0
1           1             0            0            0
2           0             0            0            1
3           0             1            0            0
4           0             0            1            0
5           0             0            1            0
6           0             0            0            1