<a href="https://colab.research.google.com/github/eashwardarur/DA/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing
ENCODING

Label Encoding

In [1]:
#Importing the modules
import pandas as pd
#scikit-learn its an library
#preprocessing module
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#LabelEncoder is class

In [2]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [3]:
df['Product'].unique()

array(['Watch', 'Mouse', 'stove', 'shoe'], dtype=object)

In [4]:
le=LabelEncoder()

In [5]:
#fit will learn the data,identify the unique vales,sort them and map them
#transform will transfrom the data
#.fit() and .transform()
#fit_transform accepts one positional argument
df['Product']=le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2

One Hot Encoder

In [6]:
import pandas as pd
#scikit-learn its an library
#preprocessing module
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
#OneHotEncoder is class

In [7]:
df1=pd.DataFrame({
    'Gadgets':['Watch','Mobile','Mobile','mobile','Tablets','ipad','Watch']

})
df

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2

In [8]:
data= ohe.fit_transform(df1[['Gadgets']])
name=ohe.get_feature_names_out(['Gadgets'])
df1= pd.DataFrame(data,columns=name)

In [9]:
df1

,Gadgets_Mobile,Gadgets_Tablets,Gadgets_Watch,Gadgets_ipad,Gadgets_mobile
0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,1.0,0.0,0.0

In [10]:
data

array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [11]:
name

array(['Gadgets_Mobile', 'Gadgets_Tablets', 'Gadgets_Watch',
       'Gadgets_ipad', 'Gadgets_mobile'], dtype=object)

Examples on OneHotEncoder

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df3=pd.DataFrame({'Batches':['A1','A1','M24','M168','M19','M19','M24']}
                )
ohe=OneHotEncoder(sparse_output=False)
data8=ohe.fit_transform(df3[['Batches']])
name=ohe.get_feature_names_out(['Batches'])
df3=pd.DataFrame(data8,columns=name)
df3

   Batches_A1  Batches_M168  Batches_M19  Batches_M24
0         1.0           0.0          0.0          0.0
1         1.0           0.0          0.0          0.0
2         0.0           0.0          0.0          1.0
3         0.0           1.0          0.0          0.0
4         0.0           0.0          1.0          0.0
5         0.0           0.0          1.0          0.0
6         0.0           0.0          0.0          1.0

In [13]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df2=pd.DataFrame({'Actors':['ALLU ARJUN','PRABHAS','SALMAN KHAN','RANBIR KAPOOR','RANVEER','ALLU ARJUN','PRABHAS']}
                )
ohe=OneHotEncoder(sparse_output=False)
dataa=ohe.fit_transform(df2[['Actors']])
name=ohe.get_feature_names_out(['Actors'])
df2=pd.DataFrame(dataa,columns=name)
df2

,Actors_ALLU ARJUN,Actors_PRABHAS,Actors_RANBIR KAPOOR,Actors_RANVEER,Actors_SALMAN KHAN
0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,0.0,0.0
6,0.0,1.0,0.0,0.0,0.0

Without using OneHotEncoder()

*   Using only pandas

In [14]:
import pandas as pd
df0=pd.DataFrame({'Actors':['ALLU ARJUN','PRABHAS','SALMAN KHAN','RANBIR KAPOOR','RANVEER','ALLU ARJUN','PRABHAS']}
                )
df0_Encoded=pd.get_dummies(df0,columns=['Actors'],dtype=int)
df0_Encoded

,Actors_ALLU ARJUN,Actors_PRABHAS,Actors_RANBIR KAPOOR,Actors_RANVEER,Actors_SALMAN KHAN
0,1,0,0,0,0
1,0,1,0,0,0
2,0,0,0,0,1
3,0,0,1,0,0
4,0,0,0,1,0
5,1,0,0,0,0
6,0,1,0,0,0

In [15]:
import pandas as pd
df0=pd.DataFrame({'Batches':['A1','A1','M24','M168','M19','M19','M24']}
                )
df0_Encoded=pd.get_dummies(df0,columns=['Batches'],dtype=float)
df0_Encoded

   Batches_A1  Batches_M168  Batches_M19  Batches_M24
0         1.0           0.0          0.0          0.0
1         1.0           0.0          0.0          0.0
2         0.0           0.0          0.0          1.0
3         0.0           1.0          0.0          0.0
4         0.0           0.0          1.0          0.0
5         0.0           0.0          1.0          0.0
6         0.0           0.0          0.0          1.0

In [16]:
#onehotencoding-multiple columns
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df0 = pd.DataFrame({'Batches':['A1','M24','M168','M19'], 'sizes':['s','m','l','s']})
oe = OrdinalEncoder(categories=[['A1','M19','M24','M168'],['s','m','l']])
df0[['Batches','sizes']] = oe.fit_transform(df0[['Batches','sizes']])
display(df0)

   Batches  sizes
0      0.0    0.0
1      2.0    1.0
2      3.0    2.0
3      1.0    0.0

In [4]:
#labelencoding

import pandas as pd
from sklearn.preprocessing import LabelEncoder
df8 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
df8['salary'].unique()
df8['department'].unique()
le = LabelEncoder()
df8['salary'] = le.fit_transform(df8['salary'])
le = LabelEncoder()
df8['departmemt'] = le.fit_transform(df8['department'])
df8

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary,departmemt
0,1003,2,157,3,0,1,0,sales,1,7
1,1005,5,262,6,0,1,0,sales,2,7
2,1486,7,272,4,0,1,0,sales,2,7
3,1038,5,223,5,0,1,0,sales,1,7
4,1057,2,159,3,0,1,0,sales,1,7
...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,1,8
14995,87673,2,160,3,0,1,0,support,1,8
14996,87679,2,143,3,0,1,0,support,1,8
14997,87681,6,280,4,0,1,0,support,1,8
14998,87684,2,158,3,0,1,0,support,1,8

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [5]:
#onehot encoding process
import pandas as pd
df10 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(sparse_output=False)
data5=ohe.fit_transform(df10[['salary','department']])
name5=ohe.get_feature_names_out(['salary','department'])
df10=pd.DataFrame(data5,columns=name5)
df10

,salary_high,salary_low,salary_medium,department_IT,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14995,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14997,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [18]:
#ordinal encoding
import pandas as pd
df11= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['medium', 'low','high']])

df11['salary']= oe.fit_transform(df11[['salary']])
df11

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,1.0
1,1005,5,262,6,0,1,0,sales,0.0
2,1486,7,272,4,0,1,0,sales,0.0
3,1038,5,223,5,0,1,0,sales,1.0
4,1057,2,159,3,0,1,0,sales,1.0
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,1.0
14995,87673,2,160,3,0,1,0,support,1.0
14996,87679,2,143,3,0,1,0,support,1.0
14997,87681,6,280,4,0,1,0,support,1.0
14998,87684,2,158,3,0,1,0,support,1.0

In [12]:
df11= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [13]:
df11

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low